
golden_set_path = "docs/REKANVAULT_GOLDEN_SET.md"

with open(golden_set_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

new_lines = []
inserted_discipline = False
for line in lines:
    new_lines.append(line)
    if "| 2026-08-05 | Q-001–Q-100 | Initial Batch Creation |" in line and not inserted_discipline:
        new_lines.append("| 2026-08-06 | Q-101–Q-164 | Batch 2 Creation | Grounded on raw corpus scan (TEMPORAL, SYNTHESIS, MULTIHOP, CONFLICT, INSUFFICIENT categories) per RV-DEC-0015 | Sigit / Antigravity |\n")
        inserted_discipline = True

# Find where Q-100 ends or Benchmark Metric Targets section starts
content_text = "".join(new_lines)

# Split before Benchmark Metric Targets section if present
if "## Benchmark Metric Targets" in content_text:
    parts = content_text.split("## Benchmark Metric Targets")
    top_part = parts[0]
    bottom_part = "## Benchmark Metric Targets" + parts[1]
else:
    top_part = content_text
    bottom_part = ""

batch_2_text = """
---

## Golden Question Batch 2 (Q-101 to Q-164)

| ID | Category | Question | Target Source / Path | Expected Answer / Evidence Key |
|---|---|---|---|---|
| `Q-101` | TEMPORAL | "Kapan notulensi Rapat Mujjadid (Core) 2026 dilaksanakan dan apa peranan struktur core yang disepakati?" | `mujaddid/raw-retrievals/mujaddid-conversation-retrieval-partial.json` (`Infrastruktur GP.pdf`) | Rapat dilaksanakan Minggu 11 Januari 2026 di Dcoffecup Wiyung Surabaya. Peran core: Raja/Kaisar (Ibrahim Muhammad Isa), Perdana Mentri (Austrin Bahirsyah), Penasehat dan Perbendaharaan (Lukmanul Chakim), Jendral Garda Kedepan (Muhammad Arief Permana), Jendral Strategi (Ridho Muhamad). |
| `Q-102` | TEMPORAL | "Bagaimana riwayat perubahan peranan IMI (Ibrahim Muhammad Isa) dari LinkedIn Agustus 2025 hingga profil Dealls Februari 2026?" | `rekanmu/raw-retrievals/rekanmu-conversation-retrieval-partial.json` | Pada Agustus 2025 tercatat sebagai Co-founder / Founder at Rekanmu.id (hampir 5 tahun), sedangkan pada 27 Februari 2026 tercatat sebagai Business Development Manager di PT Rekan Makmur Utama. |
| `Q-103` | TEMPORAL | "Berapa nominal transfer keuangan Rekanmu pada 8 Maret 2026 dan ke mana tujuan transfer tersebut?" | `rekanmu/raw-retrievals/rekanmu-gmail-raw.json` | Transfer sebesar IDR 119,952,000 dikirimkan ke DAPUR NUSANTARA KOLABORA dengan berita `1008 - PT REKAN MAKMUR UTAMA`. |
| `Q-104` | TEMPORAL | "Apa notifikasi keuangan dan anggaran yang diterima oleh rekanmu.digital@gmail.com pada Mei 2023?" | `rekanmu/raw-retrievals/rekanmu-gmail-raw.json` | Pada 22 Mei 2023 menerima undangan berbagi spreadsheet `Salinan dari Student Budget Template` dan `Salinan dari Business Budget Template`. |
| `Q-105` | TEMPORAL | "Pemberitahuan penghapusan akun apa yang diterima Rekanmu pada 23 Oktober 2023?" | `rekanmu/raw-retrievals/rekanmu-gmail-raw.json` | Notifikasi dari Canva bahwa tim `rekanmu` dijadwalkan untuk dihapus (scheduled for deletion) dalam waktu 14 hari. |
| `Q-106` | TEMPORAL | "Kapan notifikasi penggabungan anggota baru ke tim Miro GP Website team tercatat untuk Imi dan Fahrizal Fikri?" | `mujaddid/raw-retrievals/mujaddid-gmail-raw.json` | Undangan tim Miro terjadi 6 Januari 2024; Imi Hscb & Gerakan Pembaru Mujaddid bergabung 9 Januari 2024; Fahrizal Fikri bergabung 19 Maret 2024. |
| `Q-107` | TEMPORAL | "Bagaimana perkembangan jumlah pengikut LinkedIn untuk Gerakan Pembaru dan Rekanmu pada Mei 2024?" | `gerakan-pembaru/raw-retrievals/gerakan-pembaru-gmail-raw.json` & `rekanmu/raw-retrievals/rekanmu-gmail-raw.json` | Pada 14 Mei 2024 Gerakan Pembaru mendapatkan pengikut pertama (+1 follower), dan pada 16 Mei 2024 Rekanmu mendapatkan pengikut pertama (+1 follower). |
| `Q-108` | TEMPORAL | "Kapan penguncian arsitektur holding 'Rekan' oleh PT Rekan Makmur Utama dilakukan menurut catatan percakapan?" | `rekanmu/raw-retrievals/rekanmu-conversation-retrieval-partial.json` | Pada 27 Juni 2026, PT Rekan Makmur Utama mengunci arsitektur holding "Rekan" (RekanOtomasi, RekanPangan, RekanHealth, dll). |
| `Q-109` | TEMPORAL | "Kapan pembaharuan arsitektur ekosistem Rekan Makmur Utama menjadi 38 domain dan 6 layer disimpan?" | `rekanmu/raw-retrievals/rekanmu-conversation-retrieval-partial.json` | Pada 29 Juni 2026, arsitektur 38 domain dalam 6 layer dan 8 sub-domain RekanData dikunci ke dalam memori. |
| `Q-110` | TEMPORAL | "Kapan perancangan sistem intelijen SLEMAN sebagai pengorkestra ekosistem RMU dan Gerakan Pembaru dicatat?" | `mujaddid/raw-retrievals/mujaddid-conversation-retrieval-partial.json` | Pada 12 Juli 2026, SLEMAN dirancang sebagai core intelligence system yang mengorkestrasi ekosistem RMU dan Gerakan Pembaru. |
| `Q-111` | TEMPORAL | "Berapa lama riwayat email notifikasi keamanan Google tersimpan untuk rekanmu.digital@gmail.com?" | `rekanmu/raw-retrievals/rekanmu-gmail-raw.json` | Email notifikasi keamanan Google tersimpan dari 5 Oktober 2022 hingga 11 Maret 2024. |
| `Q-112` | TEMPORAL | "Kapan permohonan penghapusan/penolakan anggota tim Canva tercatat pada log email Rekanmu?" | `rekanmu/raw-retrievals/rekanmu-gmail-raw.json` | Notifikasi penolakan undangan anggota baru Canva terjadi pada 1 Desember 2022. |
| `Q-113` | SYNTHESIS | "Bagaimana pembagian peran strategis dan hubungan entitas antara Gerakan Pembaru dengan PT Rekan Makmur Utama?" | `gerakan-pembaru/raw-retrievals/gerakan-pembaru-conversation-retrieval-partial.json` & `rekanmu/original-files/RMU_Master_Strategic_Prospectus_2046.html` | Gerakan Pembaru memberi arah ideologis/nilai dasar; RMU membangun kekuatan ekonomi sebagai PT Holding. Kedua entitas berhubungan secara misi dan interface, namun tidak dicampur sebagai satu entitas legal atau satu pembukuan. |
| `Q-114` | SYNTHESIS | "Apa saja peranan Ibrahim Muhammad Isa yang terdaftar pada struktur GP Core, RMU, dan sistem SLEMAN?" | `mujaddid/raw-retrievals/mujaddid-conversation-retrieval-partial.json`, `rekanmu/raw-retrievals/rekanmu-conversation-retrieval-partial.json`, & `member_raw_archive/ibrahim-muhammad-isa/infrastruktur-gp-name-matches-raw.txt` | Di GP Core menjabat Raja/Kaisar; di RMU menjabat Business Development Manager / Founder; di sistem intelijen menjabat pembaca dan pengorkestra ekosistem SULAIMAN/SLEMAN. |
| `Q-115` | SYNTHESIS | "Bagaimana keterkaitan antara proyek biostimulan Gracilaria Kementan dengan visi agrokultur Gerakan Pembaru?" | `gerakan-pembaru/original-files/gracilaria_biostimulant_kementan_pitchdeck.pptx` & `gerakan-pembaru/original-files/Infrastruktur GP.pdf` | Proyek biostimulan Gracilaria merupakan bentuk operasionalisasi pilar ke-10 (Agrokultur dan Perairan) dalam 12 bidang Garis Besar Haluan Yayasan GP. |
| `Q-116` | SYNTHESIS | "Apa perbedaan fokus antara proyek Gracilaria Kementan dengan sistem manufaktur hijau rumput laut Rekanmu?" | `gerakan-pembaru/original-files/gracilaria_biostimulant_kementan_pitchdeck.pptx` & `rekanmu/original-files/Seaweed_Green_Manufacturing_System.pptx` | Gracilaria biostimulant berfokus pada usulan aplikasi pupuk hayati ke Kementan, sedangkan Seaweed Green Manufacturing System berfokus pada arsitektur manufaktur hijau industri untuk komersialisasi RMU. |
| `Q-117` | SYNTHESIS | "Bagaimana susunan 5 pejabat utama Struktur Core Gerakan Pembaru beserta nama anggotanya?" | `mujaddid/raw-retrievals/mujaddid-conversation-retrieval-partial.json` & `member_raw_archive/members-index.json` | Raja/Kaisar (Ibrahim Muhammad Isa), Perdana Mentri (Austrin Bahirsyah), Penasehat & Perbendaharaan (Lukmanul Chakim), Jendral Garda Kedepan (Muhammad Arief Permana), Jendral Strategi (Ridho Muhamad). |
| `Q-118` | SYNTHESIS | "Apa saja 3 pondasi utama dan 12 bidang pilar Gerakan Pembaru menurut Infrastruktur GP?" | `gerakan-pembaru/original-files/Infrastruktur GP.pdf` & `gerakan-pembaru/raw-retrievals/gerakan-pembaru-conversation-retrieval-partial.json` | 3 pondasi: HablumminAllah, Hablumminannas, HablumminalAlam. 12 bidang: Spiritual & Ideologi; Pendidikan & Kaderisasi; Budaya, Seni & Estetika; Sosial & Kesehatan; Administrasi & Perbendaharaan; Politik, Hukum & Diplomasi; Ekonomi & Aset; Pertahanan; Sains, Riset & Tata Ruang; Agrokultur & Perairan; Lingkungan & Energi; Teknologi & Industri. |
| `Q-119` | SYNTHESIS | "Bagaimana keterlibatan Fachrizal Fikri dalam struktur GP dan platform kerja Miro?" | `member_raw_archive/fachrizal-fikri/infrastruktur-gp-name-matches-raw.txt` & `mujaddid/raw-retrievals/mujaddid-gmail-raw.json` | Tercatat sebagai Anggota dalam Struktur Layer `Infrastruktur GP.pdf` dan bergabung ke tim Miro GP Website team pada 19 Maret 2024. |
| `Q-120` | SYNTHESIS | "Apa alamat email pemulihan yang digunakan untuk akun Google rekanmu.digital@gmail.com?" | `rekanmu/raw-retrievals/rekanmu-gmail-raw.json` & `member_raw_archive/ibrahim-muhammad-isa/README.txt` | Email pemulihan adalah `imihamengku@gmail.com`, yang dimiliki oleh IMI (Ibrahim Muhammad Isa Hamengku). |
| `Q-121` | SYNTHESIS | "Bagaimana arsitektur 6 layer holding Rekan Makmur Utama terhubung dengan RekanData?" | `rekanmu/raw-retrievals/rekanmu-conversation-retrieval-partial.json` & `rekanmu/original-files/RMU_Master_Strategic_Prospectus_2046.html` | 6 layer (Foundation, Resource, Production, Distribution & Services, Future Tech, Civilization) membawahi 38 domain sektoral, di mana RekanData berfungsi sebagai horizontal intelligence platform dengan 8 sub-domain. |
| `Q-122` | SYNTHESIS | "Bagaimana peranan SLEMAN dibedakan antara pengetahuan internal keluarga dengan bisnis RekanMu?" | `rekanmu/raw-retrievals/rekanmu-conversation-retrieval-partial.json` & `mujaddid/raw-retrievals/mujaddid-conversation-retrieval-partial.json` | SLEMAN berfungsi sebagai sistem pengetahuan keluarga/yayasan lintas generasi, sedangkan RekanMu berfokus pada monetisasi dan komersialisasi bisnis. |
| `Q-123` | SYNTHESIS | "Apa saja dokumen prospektus RMU 2046 yang tersedia dan apa perbedaan formatnya?" | `rekanmu/original-files/RMU_Master_Strategic_Prospectus_2046.pptx` & `rekanmu/original-files/RMU_Master_Strategic_Prospectus_2046.html` | Format PPTX berisi slide presentasi prospektus strategis (88 KB), sedangkan format HTML berisi dokumen lengkap dengan master prompt dan arsitektur detail (80 KB). |
| `Q-124` | SYNTHESIS | "Bagaimana kelengkapan arsip anggota Achmad Ja'far Sodiq dalam direktori member raw archive?" | `member_raw_archive/achmad-jafar-shodiq/README.txt`, `infrastruktur-gp-name-matches-raw.txt`, & `achmad-jafar-shodiq-conversation-retrieval-partial.json` | Terdiri dari 3 berkas: README deskripsi, teks ekstraksi name match dari `Infrastruktur GP.pdf`, dan JSON parsial percakapan. |
| `Q-125` | SYNTHESIS | "Siapa anggota yang tercatat dalam daftar Anggota di Infrastruktur GP.pdf tetapi tidak tercantum pada struktur RMU?" | `member_raw_archive/jisam-krisnanditya-zulfikri-awan/infrastruktur-gp-name-matches-raw.txt` & `rekanmu/raw-retrievals/rekanmu-conversation-retrieval-partial.json` | Jisam Krisnanditya Zulfikri Awan tercatat di `Infrastruktur GP.pdf` sebagai Anggota, namun secara eksplisit dicatat tidak ada dalam daftar tim RMU. |
| `Q-126` | SYNTHESIS | "Siapa anggota yang tercantum baik pada Struktur Layer GP maupun pembahasan tim RMU?" | `member_raw_archive/muhammad-rizky-aditya/infrastruktur-gp-name-matches-raw.txt` & `rekanmu/raw-retrievals/rekanmu-conversation-retrieval-partial.json` | Muhammad Rizky Aditya tercatat sebagai Anggota di `Infrastruktur GP.pdf` dan juga terdaftar sebagai anggota tim RMU. |
| `Q-127` | SYNTHESIS | "Bagaimana gambaran 38 domain holding Rekan yang dicatat dalam dokumen percakapan RMU?" | `rekanmu/raw-retrievals/rekanmu-conversation-retrieval-partial.json` & `rekanmu/original-files/RMU_Master_Strategic_Prospectus_2046.html` | Domain terbagi dalam 6 layer, mencakup RekanData, RekanDigital, RekanInfo, RekanCloud, RekanOtomasi, RekanPangan, RekanHealth, RekanEnergi, dll. |
| `Q-128` | SYNTHESIS | "Apa saja saluran komunikasi dan manajemen kerja digital yang digunakan oleh Rekanmu?" | `rekanmu/raw-retrievals/rekanmu-gmail-raw.json` | Terbukti menggunakan Gmail (`rekanmu.digital@gmail.com`), ClickUp (undangan tim Feb 2023), Canva (tim disetujui/dihapus 2022-2023), dan LinkedIn Page. |
| `Q-129` | SYNTHESIS | "Bagaimana keterkaitan lokasi rapat Mujjadid 11 Januari 2026 dengan dokumen Infrastruktur GP?" | `mujaddid/raw-retrievals/mujaddid-conversation-retrieval-partial.json` & `gerakan-pembaru/original-files/Infrastruktur GP.pdf` | Rapat di Dcoffecup Wiyung Surabaya menghasilkan Notulensi Mujjadid (Core) 2026 yang dimuat di dalam berkas `Infrastruktur GP.pdf`. |
| `Q-130` | SYNTHESIS | "Bagaimana rekam jejak peran Sigit Dani Perkasa dalam arsip Gerakan Pembaru?" | `member_raw_archive/sigit-dani-perkasa/infrastruktur-gp-name-matches-raw.txt` & `member_raw_archive/sigit-dani-perkasa/sigit-dani-perkasa-conversation-retrieval-partial.json` | Terdaftar sebagai Anggota di `Infrastruktur GP.pdf` dan memiliki catatan pencocokan nama serta percakapan parsial. |
| `Q-131` | SYNTHESIS | "Apa saja dokumen yang mereplikasi berkas PDF Infrastruktur GP secara identik di seluruh corpus?" | `gerakan-pembaru/original-files/Infrastruktur GP.pdf`, `mujaddid/original-files/Infrastruktur GP.pdf`, & `rekanmu/original-files/Infrastruktur GP.pdf` | Berkas PDF 282,394 bytes tersebut ada secara identik di sub-folder `original-files` pada ketiga direktori (GP, Mujaddid, Rekanmu). |
| `Q-132` | SYNTHESIS | "Bagaimana total jumlah anggota yang terindeks dalam members-index.json dibandingkan folder member archive?" | `member_raw_archive/members-index.json` & `member_raw_archive/*/` | Indeks mencatat 14 entri anggota (13 folder anggota individu + index file), mulai dari Ibrahim Muhammad Isa hingga Muhammad Rizky Aditya. |
| `Q-133` | SYNTHESIS | "Apa saja 3 direktori utama penyimpan file mentah dalam struktur archive RekanVault?" | `gerakan-pembaru/`, `mujaddid/`, `rekanmu/` | Ketiga direktori tersebut menyimpan `original-files`, `raw-retrievals`, serta `README.txt`. |
| `Q-134` | SYNTHESIS | "Bagaimana peran Austrin Bahirsyah digambarkan dalam notulensi GP Core dan indeks anggota?" | `member_raw_archive/austrin-bahirsyah/infrastruktur-gp-name-matches-raw.txt` & `member_raw_archive/members-index.json` | Dalam notulensi GP Core ditulis `Perdana Mentri : Austrin Bahirsyah`, dan dalam `members-index.json` dicatat alias `PM Utin`. |
| `Q-135` | MULTIHOP | "Siapa tokoh yang menjabat sebagai Raja/Kaisar di GP Core sekaligus Business Development Manager di PT Rekan Makmur Utama?" | `mujaddid/raw-retrievals/mujaddid-conversation-retrieval-partial.json` & `rekanmu/raw-retrievals/rekanmu-conversation-retrieval-partial.json` | Ibrahim Muhammad Isa (Ibrahim Muhammad Isa Sulaiman Hamengku Suryo Cokro Bahwono Arjuno Saputro Dewo). |
| `Q-136` | MULTIHOP | "Siapa pejabat GP Core yang memegang posisi Penasehat dan Perbendaharaan dan memiliki alias Khakkhok?" | `member_raw_archive/lukmanul-chakim/infrastruktur-gp-name-matches-raw.txt` & `member_raw_archive/members-index.json` | Lukmanul Chakim (Lukman Nul Chakim). |
| `Q-137` | MULTIHOP | "Siapa yang menjabat Jendral (Garda Kedepan) dalam GP Core dan dikenal dengan alias Ayip?" | `member_raw_archive/muhammad-arief-permana/infrastruktur-gp-name-matches-raw.txt` & `member_raw_archive/members-index.json` | Muhammad Arief Permana (Jend. Ayip). |
| `Q-138` | MULTIHOP | "Siapa Perdana Menteri GP Core yang memiliki alias PM Utin?" | `member_raw_archive/austrin-bahirsyah/infrastruktur-gp-name-matches-raw.txt` & `member_raw_archive/members-index.json` | Austrin Bahirsyah. |
| `Q-139` | MULTIHOP | "Siapa Jendral Strategi (Ahli Strategi) dalam Struktur Core GP hasil notulensi Wiyung 2026?" | `member_raw_archive/ridho-muhamad/infrastruktur-gp-name-matches-raw.txt` & `mujaddid/raw-retrievals/mujaddid-conversation-retrieval-partial.json` | Ridho Muhamad. |
| `Q-140` | MULTIHOP | "Anggota GP mana yang diundang ke tim Miro pada Maret 2024 dan tercatat di Struktur Layer PDF?" | `mujaddid/raw-retrievals/mujaddid-gmail-raw.json` & `member_raw_archive/fachrizal-fikri/infrastruktur-gp-name-matches-raw.txt` | Fachrizal Fikri. |
| `Q-141` | MULTIHOP | "Sistem platform horizontal apa yang menghubungkan 38 domain holding Rekan Makmur Utama?" | `rekanmu/raw-retrievals/rekanmu-conversation-retrieval-partial.json` | RekanData (membawahi 8 sub-domain inteligensi). |
| `Q-142` | MULTIHOP | "Apa nama sistem intelijen yang bertugas mengorkestrasi ekosistem RMU dan Gerakan Pembaru?" | `mujaddid/raw-retrievals/mujaddid-conversation-retrieval-partial.json` | SLEMAN / SULAIMAN. |
| `Q-143` | MULTIHOP | "Alamat email mana yang menjadi pemulihan untuk akun rekanmu.digital@gmail.com?" | `rekanmu/raw-retrievals/rekanmu-gmail-raw.json` | `imihamengku@gmail.com`. |
| `Q-144` | MULTIHOP | "Instansi pemerintah mana yang menjadi sasaran pitchdeck biostimulan rumput laut Gracilaria dari GP?" | `gerakan-pembaru/original-files/gracilaria_biostimulant_kementan_pitchdeck.pptx` | Kementerian Pertanian (Kementan). |
| `Q-145` | MULTIHOP | "Siapa anggota yang tercatat dalam daftar Anggota Infrastruktur GP tetapi dikonfirmasi tidak ada dalam tim struktur RMU?" | `member_raw_archive/jisam-krisnanditya-zulfikri-awan/infrastruktur-gp-name-matches-raw.txt` & `rekanmu/raw-retrievals/rekanmu-conversation-retrieval-partial.json` | Jisam Krisnanditya Zulfikri Awan. |
| `Q-146` | MULTIHOP | "Entitas PT apakah yang ditunjuk sebagai PT Holding untuk membangun kekuatan ekonomi bagi Gerakan Pembaru?" | `gerakan-pembaru/raw-retrievals/gerakan-pembaru-conversation-retrieval-partial.json` & `Infrastruktur GP.pdf` | PT Rekan Makmur Utama (Rekanmu). |
| `Q-147` | CONFLICT | "Bagaimana variasi ejaan nama kelompok 'Mujaddid' dalam dokumen notulensi dan log pencarian?" | `mujaddid/raw-retrievals/mujaddid-gmail-raw.json` & `Infrastruktur GP.pdf` | Berkas sumber memuat ejaan "Mujaddid" dan "Mujjadid" (misal: "Notulensi Mujjadid (Core)" dan "Notulensi Mujaddid (core) 2026"). Kedua ejaan valid sesuai dokumen sumber. |
| `Q-148` | CONFLICT | "Apa saja bentuk nama resmi dan variasi ejaan dari entitas Gerakan Pembaru dalam berkas korpus?" | `gerakan-pembaru/raw-retrievals/gerakan-pembaru-gmail-raw.json` & `Infrastruktur GP.pdf` | Terdapat tiga variasi ejaan valid: "Gerakan Pembaru", "Gerakan Pembaharu", dan "Gerakan Pembaru Maju". |
| `Q-149` | CONFLICT | "Bagaimana ejaan nama anggota Lukmanul Chakim pada indeks anggota dan berkas teks?" | `member_raw_archive/members-index.json` & `member_raw_archive/lukmanul-chakim/infrastruktur-gp-name-matches-raw.txt` | Indeks mencatat dua variasi ejaan resmi: "Lukmanul Chakim" dan "Lukman Nul Chakim". |
| `Q-150` | CONFLICT | "Bagaimana penulisan ejaan nama Achmad Ja'far Sodiq pada sumber indeks dan pencocokan teks?" | `member_raw_archive/members-index.json` & `member_raw_archive/achmad-jafar-shodiq/infrastruktur-gp-name-matches-raw.txt` | Berkas sumber mencatat dua variasi ejaan: "Achmad Ja’far Sodiq" (dengan apostrof kurva) dan "Achmad Ja'far Shodiq" (dengan sh). |
| `Q-151` | CONFLICT | "Apa saja sebutan nama perusahaan commercial holding yang muncul pada berkas Rekanmu?" | `rekanmu/raw-retrievals/rekanmu-gmail-raw.json`, `Infrastruktur GP.pdf`, & `rekanmu-conversation-retrieval-partial.json` | Disebut sebagai "Rekanmu", "PT Rekan Makmur Utama", dan holding "Rekan". Ketiganya merujuk pada entitas komersial yang sama. |
| `Q-152` | CONFLICT | "Apakah judul sub-bab struktur pada Infrastruktur GP.pdf tertulis 'Struktur Core' atau 'Stuktur Core'?" | `member_raw_archive/lukmanul-chakim/infrastruktur-gp-name-matches-raw.txt` (`Infrastruktur GP.pdf`) | Teks asli dokumen memuat variasi tipografi "Stuktur Core:" (tanpa r) di samping istilah standar "Struktur Layer". Kedua variasi merupakan kutipan teks sah. |
| `Q-153` | CONFLICT | "Apakah gelar kepemimpinan tertinggi dalam GP Core disebut sebagai Raja atau Kaisar?" | `mujaddid/raw-retrievals/mujaddid-conversation-retrieval-partial.json` (`Infrastruktur GP.pdf`) | Teks sumber menuliskan gelar secara gabungan "Raja/Kaisar", sehingga kedua sebutan sah menurut sumber. |
| `Q-154` | CONFLICT | "Bagaimana variasi panjang nama untuk pendiri Ibrahim Muhammad Isa dalam korpus?" | `member_raw_archive/members-index.json` & `rekanmu/raw-retrievals/rekanmu-gmail-raw.json` | Terdapat nama pendek ("Ibrahim Muhammad Isa" / "IMI Hamengku" / "Imi Hscb") dan nama lengkap 12 kata ("Ibrahim Muhammad Isa Sulaiman Hamengku Suryo Cokro Bahwono Arjuno Saputro Dewo"). Both valid. |
| `Q-155` | CONFLICT | "Apakah Garis Besar Haluan Yayasan (GBHY) dibagi menjadi 12 bidang atau 5 bidang?" | `gerakan-pembaru/original-files/Infrastruktur GP.pdf` & `gerakan-pembaru-conversation-retrieval-partial.json` | Berkas `Infrastruktur GP.pdf` menyebut 12 bagian/bidang di bawah 3 pondasi, sedangkan log percakapan menyebut istilah "five fields, twelve pillars". |
| `Q-156` | CONFLICT | "Apakah Gerakan Pembaru dan PT Rekan Makmur Utama merupakan satu entitas legal yang sama atau terpisah?" | `Infrastruktur GP.pdf` & `rekanmu/original-files/RMU_Master_Strategic_Prospectus_2046.html` | `Infrastruktur GP.pdf` menunjuk RMU sebagai PT Holding, sedangkan `RMU_Master_Strategic_Prospectus_2046.html` menegaskan keduanya tidak dicampur sebagai satu entitas legal atau satu buku pembukuan. |
| `Q-157` | CONFLICT | "Bagaimana sebutan nama peranan untuk Austrin Bahirsyah antara notulensi resmi dan alias indeks?" | `member_raw_archive/austrin-bahirsyah/infrastruktur-gp-name-matches-raw.txt` & `member_raw_archive/members-index.json` | Notulensi resmi mencatat "Perdana Mentri : Austrin Bahirsyah", sedangkan indeks anggota mencatat alias "PM Utin". |
| `Q-158` | CONFLICT | "Bagaimana sebutan nama peranan untuk Muhammad Arief Permana antara teks notulensi dan alias indeks?" | `member_raw_archive/muhammad-arief-permana/infrastruktur-gp-name-matches-raw.txt` & `member_raw_archive/members-index.json` | Teks notulensi mencatat "Jendral (Garda Kedepan) : Muhammad Arief Permana", sedangkan alias indeks mencatat "Jend. Ayip" / "Ayip". |
| `Q-159` | INSUFFICIENT | "Apakah tersimpan ekspor riwayat percakapan lengkap ChatGPT untuk anggota dalam member_raw_archive?" | `member_raw_archive/*/README.txt` & `*-conversation-retrieval-partial.json` | `INSUFFICIENT_EVIDENCE` — Berkas README dan JSON secara eksplisit memberi peringatan: "The conversation file is a partial retrieval output, not a complete ChatGPT account export." Riwayat percakapan lengkap tidak tersedia. |
| `Q-160` | INSUFFICIENT | "Di mana isi halaman web dan basis data Notion milik Gerakan Pembaru dalam arsip mentah korpus?" | `gerakan-pembaru/raw-retrievals/gerakan-pembaru-conversation-retrieval-partial.json` | `INSUFFICIENT_EVIDENCE` — Catatan pembatasan sumber secara eksplisit menyatakan "exclude all Notion content". Konten Notion tidak dimasukkan dalam ZIP korpus mentah ini. |
| `Q-161` | INSUFFICIENT | "Bagaimana rincian laporan keuangan lengkap dan neraca laba rugi PT Rekan Makmur Utama tahun 2025-2026?" | `rekanmu/raw-retrievals/rekanmu-gmail-raw.json` | `INSUFFICIENT_EVIDENCE` — Hanya ditemukan satu catatan transfer IDR 119,952,000 pada 8 Maret 2026 ke Dapur Nusantara Kolabora; neraca audit dan pembukuan laba rugi lengkap tidak tersedia di korpus mentah. |
| `Q-162` | INSUFFICIENT | "Berapa URL asli dan judul percakapan awal tempat Notulensi Mujjadid (Core) 11 Januari 2026 diambil?" | `mujaddid/raw-retrievals/mujaddid-conversation-retrieval-partial.json` | `INSUFFICIENT_EVIDENCE` — Berkas metadata menyatakan: "conversation title/URL and original chat timestamps were not present in the retrieved file metadata." |
| `Q-163` | INSUFFICIENT | "Di mana riwayat biografi lengkap dan profil pribadi para anggota Gerakan Pembaru tersimpan?" | `member_raw_archive/*/README.txt` | `INSUFFICIENT_EVIDENCE` — Berkas README tiap anggota menegaskan: "The text file preserves source wording around literal name matches; no biography or synthesized profile was created." |
| `Q-164` | INSUFFICIENT | "Bagaimana spesifikasi kode sumber dan arsitektur API dari sistem SLEMAN?" | `gerakan-pembaru/raw-retrievals/gerakan-pembaru-gmail-raw.json` & `rekanmu-conversation-retrieval-partial.json` | `INSUFFICIENT_EVIDENCE` — SLEMAN hanya dijelaskan secara konsep sebagai sistem intelijen / pengetahuan keluarga; kode sumber dan repositori teknis SLEMAN tidak ada di korpus. |

---

## Findings on Baseline Q-001–Q-100

A thorough audit of the baseline set (Q-001 to Q-100) against the raw source filesystem identified the following discrepancies. Per RV-DEC-0015 guidelines, Q-001 to Q-100 have been left untouched, and issues are documented here for future reconciliation:

1. **Path Location Discrepancy for Member Archives**:
   - **Baseline Target Paths**: Cited paths like `gerakan-pembaru/member_raw_archive/<member_folder>/...` (e.g. Q-005, Q-006–Q-018, Q-031, Q-034, Q-036, Q-039, Q-051, Q-055, Q-084, Q-087, Q-091, Q-099).
   - **Actual Corpus Reality**: `member_raw_archive` is a top-level independent archive folder (`member_raw_archive/` or `member-raw-source-archive/member_raw_archive/`), not nested under `gerakan-pembaru/`.

2. **Over-generalized Multi-Location Citation in Q-040**:
   - **Baseline Answer**: States `Infrastruktur GP.pdf` is present in `gerakan-pembaru` and `mujaddid`.
   - **Actual Corpus Reality**: `Infrastruktur GP.pdf` is present in all **three** raw archives (`gerakan-pembaru/original-files/`, `mujaddid/original-files/`, and `rekanmu/original-files/`).

3. **Wildcard Path Citation in Q-059**:
   - **Baseline Target Path**: Cites `*/original-files/Infrastruktur GP.pdf`.
   - **Actual Corpus Reality**: Citation resolution benchmarking requires exact, non-wildcard relative file paths for deterministic 100% citation matching.
"""

final_content = top_part + batch_2_text + "\n" + bottom_part

with open(golden_set_path, "w", encoding="utf-8") as f:
    f.write(final_content)

print("Successfully written Batch 2 to REKANVAULT_GOLDEN_SET.md")
